config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do
    root 'posts#index'
    resources :posts
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  mount_uploader :image, ImageUploader
  validates :title, :summary, :body, presence: true #проверка на зоплненые поля
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  add_flash_types :success, :danger, :info, :warning
  before_action :set_locale

  private

  def set_locale
    I18n.locale = params[:locale] || I18n.default_locale
  end

  def default_url_options(options = {})
    { locale: I18n.locale }.merge options
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :authenticate_user!, except: [:index, :show]

  before_action :set_post, only: [ :show, :edit, :update, :destroy]

  def index
    @posts = Post.all
  end

  def myindex
    @posts = Post.all
    if current_user != nil
      @posts = Post.where('user_id== ?', current_user.id).order(:id)
    end
  end

  def show

  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    if @post.save
      redirect_to @post, success: 'Post successfully created'
    else
      render :new, danger:  'Post not created'
    end
  end

  def edit
  end

  def update
    if @post.user_id == current_user.id && @post.update(post_params)
      redirect_to @post, success: 'Post successfully updated'
    else
      render :edit, danger:  'Post not updated'
    end
  end

  def destroy
    @post.destroy
    redirect_to posts_path, success: 'Post successfully deleted'
  end

  private

  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:user_id, :title, :summary, :body, :image)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def bootstrap_class_for(name)
    { success:"alert-success",
      error:  "alert-danger",
      danger: "alert-danger",
      alert:  "alert-warning",
      notice: "alert-info"
    }[name.to_sym] || name
  end

end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Lab13</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <div class="container">
      <nav class="navbar navbar-expand-lg navbar-light bg-light" style="background-color: #e3f2fd;">
        <div class="collapse navbar-collapse" id="navbarText">
          <table>
            <tr>
              <th> <%= link_to t('.allp'), posts_path, class: 'btn btn-outline-primary' %> </th>
              <% if user_signed_in? %>
                <th> <%= link_to t('.newp'), new_post_path, class: 'btn btn-outline-primary' %> </th>
              <% end %>
            </tr>
          </table>
        </div>

        <div class="navbar-nav pull-xs-right">
          <table>
            <tr>
              <% if user_signed_in? %>
                <th> <a> <%= button_to t('.edit'), edit_user_registration_path, :method => "get", class: "btn btn-outline-warning" %> </a> </th>
                <th> <a> <%= button_to t('.sout'), destroy_user_session_path, method: :delete, class: "btn btn-outline-warning" %> </a> </th>
              <% else %>
              <th> <a> <%= link_to t('.sin'), new_user_session_path, class: "btn btn-outline-info" %> </a> </th>
              <th> <a> <%= link_to t('.regg'), new_user_registration_path, class: "btn btn-outline-info" %> </a> </th>
              <% end %>
              <th> <%= link_to "Рус", { locale: :ru }, class: "btn btn-outline-secondary" %> </th>
              <th> <%= link_to "En", { locale: :en }, class: "btn btn-outline-secondary" %> </th>
            </tr>
          </table>
        </div>

      </nav>
    </div>

    <div class="container main">
      <div class="row">
        <div class="col-md-12">
          <% flash.each do |name, message| %>
            <div class="alert <%= bootstrap_class_for(name) %>">
              <button class="close" data-dismiss="alert">&times</button>
              <%= message %>
            </div>
          <% end %>
        </div>
      </div>
      <%= yield %>
    </div>

  </body>
</html>

app/views/posts/_disqus.html.erb
<div id="disqus_thread"></div>
<script>
  var disqus_config = function () {
    <%# <1%# this.page.url = '<%= request.base.url + request.original_fullpath %2>'; %>
    this.page.url = 'http://localhost.com<%= request.original_fullpath %>';
    this.page.identifier = '<%= @post.id %>';
  };
  (function() { // DON'T EDIT BELOW THIS LINE
    var d = document, s = d.createElement('script');
    s.src = '//blogdev.disqus.com/embed.js';
    s.setAttribute('data-timestamp', +new Date());
    (d.head || d.body).appendChild(s);
  })();
</script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>

app/views/posts/_form.html.erb
<% if @post.errors.any? %>
  <div class=" alert alert-danger">
    <h5> <%= t('common.errors') %> </h5>
    <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li> <%= message %> </li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_for @post, html: { multipart: true } do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :summary %>
    <%= f.text_area :summary, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :body %>
    <%= f.text_area :body, class: 'form-control editor' %>
  </div>

  <div class="form-group">
    <%= f.file_field :image, class: "btn btn-success"%>
  </div>

  <div class="form-group">
    <%= f.submit t('.submit', action: @post.new_record? ? t('common.create') : t('common.edit')), class: 'btn btn-primary'%>
    <%= link_to t('common.back'), :back, class: 'btn btn-outline-secondary' %>
  </div>

<% end %>

app/views/posts/_post.html.erb
<article class="post">

  <section class="post-head">
    <h2><%= link_to post.title, post_path(post) %></h2>
    <small>
      <table>
        <tr>
          <th> <time><%= post.created_at.to_date.strftime("%d %B, %Y") %></time> </th>
          <% if user_signed_in? && post.user_id == current_user.id  %>
            <th> <%= link_to t('.edit'), edit_post_path(post), :class => "btn btn-warning" %> </th>
            <th> <%= button_to t('.delete'), post_path(post), method: :delete, :class => 'btn btn-danger' %> </th>
          <% end %>
        </tr>
      </table>
    </small>
  </section>

  <section class="post-summary clearfix">
    <table>
      <tr>
        <th> <%= image_tag post.image.url(:thumb), class: 'img-show collapse' if post.image? %> </th>
        <th class='font-weight-normal'> <%= post.summary %> </th>
      </tr>
    </table>
  </section>

</article>

app/views/posts/edit.html.erb
<h1><%= t('.title') %></h1>

<%= render 'form' %>

app/views/posts/index.html.erb
<h1><%= t('.title') %></h1>

<%= render @posts %>

app/views/posts/new.html.erb
<h1><%= t('.title') %></h1>

<%= render 'form' %>

app/views/posts/show.html.erb
<article class="post">

  <section class="post-head">
    <h1><%= @post.title %></h1>
    <small>
      <table>
        <tr>
          <th> <time><%= @post.created_at.to_date.strftime("%d %B, %Y") %></time> </th>
          <% if user_signed_in? && @post.user_id == current_user.id  %>
            <th> <%= link_to t('.edit'), edit_post_path(@post), :class => "btn btn-warning" %> </th>
            <th> <%= button_to t('.delete'), post_path(@post), method: :delete, :class => 'btn btn-danger' %> </th>
          <% end %>
        </tr>
      </table>
    </small>
  </section>

  <section class="post-body">
    <%= image_tag @post.image.url(:large), class: 'img-show collapse rounded mx-auto d-block' if @post.image? %>
    <%= @post.body.html_safe %>
  </section>

</article>

<%= render 'disqus' %>